#! /usr/bin/env python

import roslib
roslib.load_manifest('servo_driver')
import rospy
import actionlib

from servo_driver.msg import set_anglesAction, set_anglesGoal


if __name__ == '__main__':
    rospy.init_node('do_dishes_client')
    client = actionlib.SimpleActionClient('do_dishes', DoDishesAction)
    client.wait_for_server()

    goal = DoDishesGoal()
    # Fill in the goal here
    client.send_goal(goal)
    client.wait_for_result(rospy.Duration.from_sec(5.0))