#!/bin/bash
PREFIX="/home/brian/ROS"
ROS_VERSION="indigo"

### Sync up launch files
echo -n "Copying launch files..."
ssh raspberrypi "mkdir -p $PREFIX/launch-files"
rsync -a launch-files raspberrypi:$PREFIX
echo "done."

### Sync up source/scripts
echo -n "Copying source files..."
ssh raspberrypi "mkdir -p $PREFIX/workspace/src"
rsync -a workspace/src raspberrypi:$PREFIX/workspace
echo "done."

### Build the workspace
echo "Building the workspace on the raspberry pi"
ssh raspberrypi "source /opt/ros/$ROS_VERSION/setup.bash; cd $PREFIX/workspace; catkin_make; catkin_make install"
echo "Workspace succesfully installed."