#! /usr/bin/env python
import struct
import serial
import time

import roslib
roslib.load_manifest('servo_driver')
import rospy



class UltrasonicArrayController:

    def __init__(self):
        pass


if __name__ == '__main__':
    rospy.init_node('ultrasonic_array')
    ultrasonic_array = UltrasonicArrayController()
    try:
        rospy.spin()
    except KeyboardInterrupt:
        print("Shutting down")
        ultrasonic_array.shutdown()