#! /usr/bin/env python
import struct
import serial
import time

import roslib
roslib.load_manifest('ultrasonic_array')
import rospy
from sensor_msgs.msg import Range



class UltrasonicArrayController:

    def __init__(self):

        out_topic = '/image_out'
        self.image_pub = rospy.Publisher(out_topic, Image)


if __name__ == '__main__':
    rospy.init_node('ultrasonic_array')
    ultrasonic_array = UltrasonicArrayController()
    try:
        rospy.spin()
    except KeyboardInterrupt:
        print("Shutting down")
        ultrasonic_array.shutdown()